name: Update Helm Chart Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} 

      - name: Set version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up Git for push
        run: |
          git config user.name "BronislavaKorolyova"
          git config user.email "bronya.korolyova@gmail.com"


      - name: Update image tag in values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${VERSION}/" flask-app/values.yaml
          git add flask-app/values.yaml
          git commit -m "Update image tag to ${VERSION}"
          git push origin HEAD:main

