apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
  labels:
    app: {{ .Release.Name }}-flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000

